version: '3.2'

services:
  hello_init:
    build: hello
    restart: always
    network_mode: bridge
    command: --ring hello --permanent-peer --peer-watch-file /peer/peer-watch-file.txt
    ports:
      - 3000
    labels:
      SERVICE_3000_CHECK_TCP: "true"
      SERVICE_3000_CHECK_INTERVAL: "60s"
      SERVICE_3000_NAME: "hello"
      SERVICE_3000_TAGS: "urlprefix-hello.*/"
    volumes:
      - type: volume
        source: peer
        target: /peer
        volume:
          nocopy: true
      - type: volume
        source: keys
        target: /hab/cache/keys
        volume:
          nocopy: true
  hello:
    image: imma/habitat
    restart: always
    network_mode: bridge
    command: --ring hello --permanent-peer --peer-watch-file /peer/peer-watch-file.txt
    depends_on:
      - hello_init
    ports:
      - 3000
    labels:
      SERVICE_3000_CHECK_TCP: "true"
      SERVICE_3000_CHECK_INTERVAL: "60s"
      SERVICE_3000_NAME: "hello"
      SERVICE_3000_TAGS: "urlprefix-hello.*/"
    volumes:
      - type: volume
        source: peer
        target: /peer
        volume:
          nocopy: true
      - type: volume
        source: keys
        target: /hab/cache/keys
        volume:
          nocopy: true
volumes:
  peer:
  keys:
