version: '3.2'

services:
  init:
    build: habitat
    restart: always
    network_mode: bridge
    command: --permanent-peer --peer-watch-file /peer/peer-watch-file.txt
    ports:
      - "9631"
    labels:
      SERVICE_9631_CHECK_TCP: "true"
      SERVICE_9631_CHECK_INTERVAL: "60s"
      SERVICE_9631_NAME: "habitat"
      SERVICE_9631_TAGS: "urlprefix-habitat.*/"
    volumes:
      - type: volume
        source: peer
        target: /peer
        volume:
          nocopy: true
      - type: volume
        source: keys
        target: /hab/cache/keys
        volume:
          nocopy: true
  peer:
    image: imma/habitat
    restart: always
    network_mode: bridge
    command: --permanent-peer --peer-watch-file /peer/peer-watch-file.txt
    volumes:
      - type: volume
        source: peer
        target: /peer
        volume:
          nocopy: true
      - type: volume
        source: keys
        target: /hab/cache/keys
        volume:
          nocopy: true
  hello:
    image: imma/habitat
    restart: always
    network_mode: bridge
    command: --peer-watch-file /peer/peer-watch-file.txt --group hello
    depends_on:
      - init
    env_file:
      - .env
    ports:
      - 9631
      - 3000
    labels:
      SERVICE_3000_CHECK_TCP: "true"
      SERVICE_3000_CHECK_INTERVAL: "60s"
      SERVICE_3000_NAME: "hello"
      SERVICE_3000_TAGS: "urlprefix-hello.*/"
      SERVICE_9631_CHECK_TCP: "true"
      SERVICE_9631_CHECK_INTERVAL: "60s"
      SERVICE_9631_NAME: "hab-hello"
      SERVICE_9631_TAGS: "urlprefix-hab-hello.*/"
    volumes:
      - type: volume
        source: peer
        target: /peer
        volume:
          nocopy: true
      - type: volume
        source: keys
        target: /hab/cache/keys
        volume:
          nocopy: true
  goodbye:
    image: imma/habitat
    restart: always
    network_mode: bridge
    command: --peer-watch-file /peer/peer-watch-file.txt --group goodbye
    depends_on:
      - init
    env_file:
      - .env
    ports:
      - 9631
      - 3000
    labels:
      SERVICE_3000_CHECK_TCP: "true"
      SERVICE_3000_CHECK_INTERVAL: "60s"
      SERVICE_3000_NAME: "goodbye"
      SERVICE_3000_TAGS: "urlprefix-goodbye.*/"
      SERVICE_9631_CHECK_TCP: "true"
      SERVICE_9631_CHECK_INTERVAL: "60s"
      SERVICE_9631_NAME: "hab-goodbye"
      SERVICE_9631_TAGS: "urlprefix-hab-goodbye.*/"
    volumes:
      - type: volume
        source: peer
        target: /peer
        volume:
          nocopy: true
      - type: volume
        source: keys
        target: /hab/cache/keys
        volume:
          nocopy: true
volumes:
  peer:
  keys:
