#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  export HAB_STUDIO_SUP=0
  local nm_volume="habitat_data_$(uname -n | perl -pe 'chomp; s{[^a-zA-Z0-9]+}{_}g')"
  dsync "$(pwd):/sync" "$nm_volume" imma/ubuntu:rsync --delete --exclude README.md --exclude .git
  export HAB_DOCKER_OPTS="-v $nm_volume:/hab/studios/src/src"
  if [[ "$#" == 0 ]]; then
    set -- enter
  fi
  hab studio -n "$@"
  docker run -v "$nm_volume:/sync" imma/ubuntu:rsync tar cfz - -C /sync results | tar xvfz -
  return 1
}

source sub "$BASH_SOURCE" "$@"
