#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  if [[ "$#" == 0 ]]; then
    export HAB_STUDIO_SUP=0
    exec hab studio sync
    return 1
  fi

  case "$(uname -s)" in
    Darwin)
      exec /usr/local/bin/hab studio "$@"
      ;;
    *)
      exec "${BOARD_PATH:-${HOME}}/hab/bin/hab" studio -D "$@"
      ;;
  esac
}

source sub "$BASH_SOURCE" "$@"
