#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  ${NOSUDO} sudo install -d -o "${USER:-ubuntu}" -g "${USER:-ubuntu}" -m 0755 /hab
  "$shome/libexec/install.sh" -v "$HABITAT_VERSION"
}

main "$@"
