#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_habitat="$(hab --version 2>/dev/null | awk '{print $2}' | cut -d/ -f1 || true)"
  jq -n --arg habitat "$ver_habitat" '{habitat: $habitat}'
}

version "$@"
